[general]
import = ["~/afs/.confs/config/alacritty/colors.toml"]

[window]
opacity = 0.9
padding = { x = 4, y = 4 }

[cursor.style]
shape = "Beam"
blinking = "Always"

[cursor]
blink_interval = 500

[font]
size = 11
glyph_offset = { x = 0, y = 0 }

